version: '3.9'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    entrypoint: dockerize -wait http://fullcycle-rocks:3000 -timeout 40s nginx -g 'daemon off;'
    ports:
      - "8080:80"
    depends_on:
      - app

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-ruth}
      MYSQL_DATABASE: fullcycle
    ports:
      - "3306:3306"
    volumes:
      - './mysql/data:/var/lib/mysql'

  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: fullcycle-rocks
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s node
    command: src/index.mjs
    environment:
      PORT: 3000
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD:-ruth}
      MYSQL_DATABASE: fullcycle
    depends_on:
      - mysql
