version: '3.9'

services:
  nginx:
    image: nginx:1.21-alpine
    ports:
      - "8080:80"
    volumes:
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - app

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-ruth}
      MYSQL_DATABASE: fullcycle
    ports:
      - "3306:3306"
    volumes:
      - './mysql/data:/var/lib/mysql'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -uroot --password=$$MYSQL_ROOT_PASSWORD

  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: fullcycle-rocks
    environment:
      PORT: 3000
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD:-ruth}
      MYSQL_DATABASE: fullcycle
    depends_on:
      mysql:
        condition: service_healthy
